# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'Odev7-ToDoApp-MVVM-RxSwift-SQLite-Repository' do
  use_frameworks!
    pod 'RxSwift', '6.5.0'
    pod 'RxCocoa', '6.5.0'
end

