# Podfile
use_frameworks!

target 'Day13-FilmlerApp-MVVM-RxSwift-Repository-Firestore' do
    pod 'RxSwift', '6.5.0'
    pod 'RxCocoa', '6.5.0'
    pod 'FirebaseFirestore'
    pod 'Kingfisher', '~> 7.0'
end